#!/usr/bin/env python

import math
import sys
import time

format_str = sys.argv[1] if len(sys.argv) > 1 else '{}'
sys.stderr.write('Writing live time to /tmp/livetime.txt\n')
f = open('/tmp/livetime.txt', 'w')
try:
    while True:
        now = time.time()
        line = format_str.format(time.strftime('%H:%M:%S', time.localtime(now)))
        f.write(line)
        sys.stderr.write('\r' + line)
        time.sleep(math.ceil(now) - now)
        f.seek(0)
except KeyboardInterrupt:
    sys.stderr.write('\n')
