#!/usr/bin/env python

import time
import sys

format_str = sys.argv[1] if len(sys.argv) > 1 else '{}'
print('Writing live time to /tmp/livetime.txt')
print('Format: ' + format_str.format(time.strftime('%H:%M:%S')))
f = open('/tmp/livetime.txt', 'w')
while True:
    f.write(format_str.format(time.strftime('%H:%M:%S')))
    time.sleep(.1)
    f.seek(0)
