#!/bin/bash

if [ "$(uname)" = Darwin ]
then
    GNU_GREP=/opt/homebrew/bin/ggrep
else
    GNU_GREP=grep
fi

APIBASE="${APIBASE:-http://localhost:1234/v1}"
MODEL="${MODEL:-meta/llama-3.3-70b}"
PROMPT="$(</dev/stdin)"

echo -n "$PROMPT"
jq --arg model "$MODEL" --arg prompt "$PROMPT" -n '{"model":$model,"prompt":$prompt,"stream":true}' | curl --json @- -Ns "$APIBASE/completions" | $GNU_GREP --line-buffered -Po '(?<=^data: )(?!\[D).*$' | jq --unbuffered -j '.choices[0].text // ""'
echo
