#!/usr/bin/env python

import random
import sys

if len(sys.argv) >= 3:
    print(random.randint(int(sys.argv[1]), int(sys.argv[2])-1))
elif len(sys.argv) >= 2:
    print(random.randint(0, int(sys.argv[1])-1))
else:
    print(random.randint(0, 32767))
